name: Push Commits to Discord Webhook
on:
  push:
    tags:
      - '*'
    paths-ignore:
      - '.github/**'
jobs:
  github-action:
    runs-on: ubuntu-latest
    env:
      CF_API_KEY: ${{ secrets.CF_API_KEY }}
      GITHUB_OAUTH: ${{ secrets.REPOOCPAT }}
    steps:
      - name: Clone Project
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Package and Release
        uses: BigWigsMods/packager@master
