name: Push Commits to Discord Webhook
on:
  push:
    paths-ignore:
      - '.github/**'
    branches:
      - main
    tags:
      - '**'
jobs:
  github-action:
    runs-on: ubuntu-latest
    env:
      GITHUB_OAUTH: ${{ secrets.GITHUB_TOKEN }}
      DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
    steps:
      - name: Clone Project
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Package and Release
        uses: BigWigsMods/packager@v2
      - name: Send file README.md to discord channel
        if: success()
        uses: sinshutu/upload-to-discord@v2.0.0
        with:
          args: ./*.zip
